### ISSUE TITLE
Can this work with FBCP?

### ISSUE THREAD

**Issue by 32teeth** [lakkatv/gamegirl-screen#2]
Would be great if we can get this to work with [Linux Framebuffer](https://github.com/tasanakorn/rpi-fbcp)

Specifically ILI9341 devices with 12/14/18 pin configurations

**Comment by Helder1981** [comment]
I totally agree and is nice to have something besides Retropie being one of the only OS with SPI support for TFT LCDs.

**Comment by kivutar** [comment]
fbcp is slow like 25fps, the method we are using allows 120fps.
